### ISSUE TITLE
Issue in building Symbolic for ARM64

### ISSUE THREAD

**Issue by akhilgupta74** [getsentry/symbolic#76]
Using symbolic for sentry on arm64 architecture.

I get the below-mentioned error:
**pip install symbolic**

```
 Running setup.py install for symbolic ... error
    Complete output from command /www/sentry/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ExkRly/symbolic/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-OXXEHA/install-record.txt --single-version-externally-managed --compile --install-headers /www/sentry/include/site/python2.7/symbolic:
    running install
    running build
    running build_py
    creating build/lib
    creating build/lib/symbolic
    copying symbolic/common.py -> build/lib/symbolic
    copying symbolic/symcache.py -> build/lib/symbolic
    copying symbolic/exceptions.py -> build/lib/symbolic
    copying symbolic/proguard.py -> build/lib/symbolic
    copying symbolic/utils.py -> build/lib/symbolic
    copying symbolic/_compat.py -> build/lib/symbolic
    copying symbolic/debuginfo.py -> build/lib/symbolic
    copying symbolic/sourcemap.py -> build/lib/symbolic
    copying symbolic/demangle.py -> build/lib/symbolic
    copying symbolic/minidump.py -> build/lib/symbolic
    copying symbolic/__init__.py -> build/lib/symbolic
    error: [Errno 2] No such file or directory

```
The package used is Symbolic 5.0.2

**Comment by jan-auer** [comment]
I know the error message is not ideal, but could you please verify that `cargo` (rust stable toolchain) is installed on your system and on the PATH? We do not build a binary wheel for symbolic arm64, so you have to build from the sdist manually. Besides that, you will need a C++11 compiler.

**Comment by akhilgupta74** [comment]
After trying to compile Symbolic Source code, this is what I get:
```
[root@localhost symbolic]# make
info: component 'rustfmt-preview' for target 'aarch64-unknown-linux-gnu' is up to date
cargo fmt -- --write-mode diff
Diff in /root/akhil/docker/P2.1/sentry/source/getsentry/symbolic/symcache/src/breakpad.rs at line 1:
 use failure::ResultExt;
-use symbolic_debuginfo::{BreakpadData, BreakpadFileRecord, BreakpadFuncRecord,
-                         BreakpadModuleRecord, BreakpadPublicRecord, BreakpadRecord, Object};
+use symbolic_debuginfo::{
+    BreakpadData, BreakpadFileRecord, BreakpadFuncRecord, BreakpadModuleRecord,
+    BreakpadPublicRecord, BreakpadRecord, Object,
+};

 use error::{ConversionError, SymCacheError, SymCacheErrorKind};

Diff in /root/akhil/docker/P2.1/sentry/source/getsentry/symbolic/symcache/src/cache.rs at line 14:
 use symbolic_demangle::Demangle;

 use error::{SymCacheError, SymCacheErrorKind};
-use types::{CacheFileHeader, CacheFileHeaderV1, CacheFileHeaderV2, CacheFilePreamble, DataSource,
-            FileRecord, FuncRecord, Seg};
+use types::{
+    CacheFileHeader, CacheFileHeaderV1, CacheFileHeaderV2, CacheFilePreamble, DataSource,
+    FileRecord, FuncRecord, Seg,
+};
 use utils::common_join_path;
 use writer;

Diff in /root/akhil/docker/P2.1/sentry/source/getsentry/symbolic/symcache/src/dwarf.rs at line 12:
 use failure::Fail;
 use fallible_iterator::FallibleIterator;
 use fnv::FnvBuildHasher;
-use gimli::{self, Abbreviations, AttributeValue, CompilationUnitHeader, DebugAbbrev,
-            DebugAbbrevOffset, DebugInfoOffset, DebugLine, DebugLineOffset, DebugRanges, DebugStr,
-            DebuggingInformationEntry, DwLang, EndianBuf, IncompleteLineNumberProgram, Range,
-            StateMachine, UnitOffset};
+use gimli::{
+    self, Abbreviations, AttributeValue, CompilationUnitHeader, DebugAbbrev, DebugAbbrevOffset,
+    DebugInfoOffset, DebugLine, DebugLineOffset, DebugRanges, DebugStr, DebuggingInformationEntry,
+    DwLang, EndianBuf, IncompleteLineNumberProgram, Range, StateMachine, UnitOffset,
+};
 use lru_cache::LruCache;

 use error::{ConversionError, SymCacheError, SymCacheErrorKind};
Diff in /root/akhil/docker/P2.1/sentry/source/getsentry/symbolic/minidump/src/cfi.rs at line 3:
 use std::io::Write;

 use failure::{Backtrace, Context, Fail, ResultExt};
-use gimli::{self, BaseAddresses, CfaRule, CieOrFde, DebugFrame, EhFrame, FrameDescriptionEntry,
-            Reader, ReaderOffset, RegisterRule, UninitializedUnwindContext, UnwindOffset,
-            UnwindSection, UnwindTable};
+use gimli::{
+    self, BaseAddresses, CfaRule, CieOrFde, DebugFrame, EhFrame, FrameDescriptionEntry, Reader,
+    ReaderOffset, RegisterRule, UninitializedUnwindContext, UnwindOffset, UnwindSection,
+    UnwindTable,
+};

 use symbolic_common::types::{Arch, DebugKind, UnknownArchError};
 use symbolic_debuginfo::{DwarfData, DwarfSection, Object};
Diff in /root/akhil/docker/P2.1/sentry/source/getsentry/symbolic/minidump/src/processor.rs at line 16:
 use utils;

 lazy_static! {
-    static ref LINUX_BUILD_RE: Regex = Regex::new(r"^Linux ([^ ]+) (.*) \w+(?: GNU/Linux)?$").unwrap();
+    static ref LINUX_BUILD_RE: Regex =
+        Regex::new(r"^Linux ([^ ]+) (.*) \w+(?: GNU/Linux)?$").unwrap();
 }

 extern "C" {
cargo build --all
   Compiling symbolic-minidump v5.0.2 (file:///root/akhil/docker/P2.1/sentry/source/getsentry/symbolic/minidump)
   Compiling symbolic-sourcemap v5.0.2 (file:///root/akhil/docker/P2.1/sentry/source/getsentry/symbolic/sourcemap)
   Compiling symbolic-symcache v5.0.2 (file:///root/akhil/docker/P2.1/sentry/source/getsentry/symbolic/symcache)
   Compiling symbolic v5.0.2 (file:///root/akhil/docker/P2.1/sentry/source/getsentry/symbolic)
error: failed to run custom build command for `symbolic-minidump v5.0.2 (file:///root/akhil/docker/P2.1/sentry/source/getsentry/symbolic/minidump)`
process didn't exit successfully: `/root/akhil/docker/P2.1/sentry/source/getsentry/symbolic/target/debug/build/symbolic-minidump-3d16ca804f6dad79/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("aarch64-unknown-linux-gnu")
TARGET = Some("aarch64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
OPT_LEVEL = Some("0")
TARGET = Some("aarch64-unknown-linux-gnu")
TARGET = Some("aarch64-unknown-linux-gnu")
HOST = Some("aarch64-unknown-linux-gnu")
HOST = Some("aarch64-unknown-linux-gnu")
TARGET = Some("aarch64-unknown-linux-gnu")
TARGET = Some("aarch64-unknown-linux-gnu")
TARGET = Some("aarch64-unknown-linux-gnu")
TARGET = Some("aarch64-unknown-linux-gnu")
HOST = Some("aarch64-unknown-linux-gnu")
HOST = Some("aarch64-unknown-linux-gnu")
CC_aarch64-unknown-linux-gnu = None
CC_aarch64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("aarch64-unknown-linux-gnu")
TARGET = Some("aarch64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("aarch64-unknown-linux-gnu")
TARGET = Some("aarch64-unknown-linux-gnu")
CC_aarch64-unknown-linux-gnu = None
HOST = Some("aarch64-unknown-linux-gnu")
CC_aarch64_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_aarch64-unknown-linux-gnu = None
CFLAGS_aarch64_unknown_linux_gnu = None
HOST = Some("aarch64-unknown-linux-gnu")
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
TARGET = Some("aarch64-unknown-linux-gnu")
HOST = Some("aarch64-unknown-linux-gnu")
CFLAGS_aarch64-unknown-linux-gnu = None
CFLAGS_aarch64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-o" "/root/akhil/docker/P2.1/sentry/source/getsentry/symbolic/target/debug/build/symbolic-minidump-c9b22f7f89b35ef0/out/third_party/breakpad/src/third_party/libdisasm/ia32_implicit.o" "-c" "third_party/breakpad/src/third_party/libdisasm/ia32_implicit.c"
DEBUG = Some("true")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-o" "/root/akhil/docker/P2.1/sentry/source/getsentry/symbolic/target/debug/build/symbolic-minidump-c9b22f7f89b35ef0/out/third_party/breakpad/src/third_party/libdisasm/ia32_settings.o" "-c" "third_party/breakpad/src/third_party/libdisasm/ia32_settings.c"
HOST = Some("aarch64-unknown-linux-gnu")
TARGET = Some("aarch64-unknown-linux-gnu")
TARGET = Some("aarch64-unknown-linux-gnu")
HOST = Some("aarch64-unknown-linux-gnu")
CC_aarch64-unknown-linux-gnu = None
CC_aarch64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("aarch64-unknown-linux-gnu")
TARGET = Some("aarch64-unknown-linux-gnu")
HOST = Some("aarch64-unknown-linux-gnu")
CFLAGS_aarch64-unknown-linux-gnu = None
CFLAGS_aarch64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-o" "/root/akhil/docker/P2.1/sentry/source/getsentry/symbolic/target/debug/build/symbolic-minidump-c9b22f7f89b35ef0/out/third_party/breakpad/src/third_party/libdisasm/x86_imm.o" "-c" "third_party/breakpad/src/third_party/libdisasm/x86_imm.c"
TARGET = Some("aarch64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("aarch64-unknown-linux-gnu")
HOST = Some("aarch64-unknown-linux-gnu")
TARGET = Some("aarch64-unknown-linux-gnu")
TARGET = Some("aarch64-unknown-linux-gnu")
HOST = Some("aarch64-unknown-linux-gnu")
CC_aarch64-unknown-linux-gnu = None
CC_aarch64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("aarch64-unknown-linux-gnu")
TARGET = Some("aarch64-unknown-linux-gnu")
HOST = Some("aarch64-unknown-linux-gnu")
CFLAGS_aarch64-unknown-linux-gnu = None
CFLAGS_aarch64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-o" "/root/akhil/docker/P2.1/sentry/source/getsentry/symbolic/target/debug/build/symbolic-minidump-c9b22f7f89b35ef0/out/third_party/breakpad/src/third_party/libdisasm/ia32_modrm.o" "-c" "third_party/breakpad/src/third_party/libdisasm/ia32_modrm.c"
cargo:warning=cc: error: third_party/breakpad/src/third_party/libdisasm/ia32_implicit.c: No such file or directory
cargo:warning=cc: error: third_party/breakpad/src/third_party/libdisasm/x86_imm.c: No such file or directory
cargo:warning=cc: error: third_party/breakpad/src/third_party/libdisasm/ia32_settings.c: No such file or directory
cargo:warning=cc: error: third_party/breakpad/src/third_party/libdisasm/ia32_modrm.c: No such file or directory
cargo:warning=cc: fatal error: no input files
cargo:warning=compilation terminated.
exit code: 4
cargo:warning=cc: fatal error: no input files
cargo:warning=compilation terminated.
exit code: 4
cargo:warning=cc: fatal error: no input files
cargo:warning=compilation terminated.
exit code: 4
cargo:warning=cc: fatal error: no input files
cargo:warning=compilation terminated.
exit code: 4

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-o" "/root/akhil/docker/P2.1/sentry/source/getsentry/symbolic/target/debug/build/symbolic-minidump-c9b22f7f89b35ef0/out/third_party/breakpad/src/third_party/libdisasm/ia32_implicit.o" "-c" "third_party/breakpad/src/third_party/libdisasm/ia32_implicit.c" with args "cc" did not execute successfully (status code exit code: 4).

', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.17/src/lib.rs:2180:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   6: cc::fail
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.17/src/lib.rs:2180
   7: cc::Build::compile
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.17/src/lib.rs:913
   8: build_script_build::main
             at minidump/build.rs:4
   9: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  10: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  11: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  12: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  13: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  14: main
  15: __libc_start_main
  16: <unknown>

warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [build] Error 101

```

Can you please have a look, and guide me further.

Regards,

**Comment by jan-auer** [comment]
It seems that you no longer try to install from the python source dist but have checked out sources manually. Did you also initialize git submodules with `git submodule update --init`? 

Also, please beware that `make` will run tests by default and not create the release build. You should run `cargo build` and `cargo build --release` to test and build, respectively.

**Comment by akhilgupta74** [comment]
Thanks for helping out.
I am able to build symbolic package now with ```cargo build --release```.
This means that source code compilation works fine.

But in my use case Sentry package is doing ```pip install symbolic``` from wheel file ```sentry-8.22.0-py27-none-any.whl```.
And this results in original errors.
Can you please guide, how can I resolve these errors in pip install too.

Regards,

**Comment by jan-auer** [comment]
With cargo / rust configured on your system, install the sdist (symbolic-x.y.z.zip) or manually pip install the `symbolic/py/` folder.

**Comment by jmreicha** [comment]
@jan-auer I know I'm late to the party, but why isn't arm64 officially supported?

**Comment by jan-auer** [comment]
The library should build on arm and arm64 without problems, we just don’t provide prebuilt python libraries as we don’t need them in Sentry. The only difference is that you need a recent rust toolchain.

**Comment by jmreicha** [comment]
Ok, thanks.  I'm attempting to build the Docker image on arm64 but running into some Rust issues.  Is there a better place to discuss?
