### ISSUE TITLE
Issue reading dsym file (caused by.. type is too big)

### ISSUE THREAD

**Issue by teddy-cha** [getsentry/symbolic#77]
Hello. 
I want to use the symbolic library for symbolication of ios crash in linux.

Then, I run a below python code. 
```python
import os
from symbolic.symcache import SymCache
from symbolic.debuginfo import FatObject

arch = 'arm64'
path = os.path.join('<PATH>')
fo = FatObject.from_path(path)
```

I get the below-mentioned error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/symbolic/debuginfo.py", line 28, in from_path
    rustcall(lib.symbolic_fatobject_open, path))
  File "/usr/local/lib/python2.7/dist-packages/symbolic/utils.py", line 87, in rustcall
    raise exc
symbolic.ObjectErrorBadObject: failed to read object file
  caused by: type is too big (1818991) for 565248
```

Is there a workaround?

**Comment by jan-auer** [comment]
Does this still happen with the latest release?
