### ISSUE TITLE
Flutter web symbolication uses `scope` instead of `name` but the `name` in some cases if not all is better

### ISSUE THREAD

**Issue by marandaneto** [getsentry/symbolic#791]
### Environment

Flutter web 3.7.x

### Steps to Reproduce

Throw exception in `async` method.

```dart
onPressed: () async {
  await Future(() {});
  throw Exception('Test exception');
},
```

More context here https://github.com/getsentry/sentry-dart/issues/1430#issuecomment-1551632816

Probably relates to https://github.com/dart-lang/sdk/issues/52483 as well

### Expected Result

Frame `at <fn> (main.dart.js:56371:16)` gets symbolicated to:

`at MainApp.build.<anonymous function>(../../../lib/main.dart 25:15)`

### Actual Result

Frame `at <fn> (main.dart.js:56371:16)` gets symbolicated to:

`at $async$$0(../../../lib/main.dart:25:15)`

**Comment by marandaneto** [comment]
@loewenheim can we do something about this during our symbolication? special case Dart/Flutter events and read the `scope` instead of the `name` when available?
